services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0
    ports:
      - 8080:8080
    command: start-dev
    volumes:
      - .:/app
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  web_bkd:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - APP_NAME="Aplikasi BKD"
      - STYLE_COLOR=purple
      - APP_URL=http://172.17.0.1:8000
      - KEYCLOAK_CLIENT_ID=test_client_bkd

  web_diknas:
    build:
      context: .
    ports:
      - 8001:8001
    volumes:
      - .:/app
    environment:
      - LARAVEL_SERVE_PORT=8001
      - APP_NAME="Aplikasi Diknas"
      - STYLE_COLOR=blue
      - APP_URL=http://172.17.0.1:8001
      - KEYCLOAK_CLIENT_ID=test_client_diknas

