services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0
    ports:
      - 8080:8080
    command: start-dev
    volumes:
      - .:/app
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  web:
    build:
      context: .
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    volumes:
      - .:/app

