services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0
    ports:
      - 8080:8080
    command: start-dev
    volumes:
      - .:/app
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

